name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    types: [review_requested]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run test
      - run: cd $GITHUB_WORKSPACE



