# This is a basic workflow to help you get started with Actions

name: Pull Request

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull_request_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: echo ${{ secrets.PAT_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
  test_build:
    runs-on: windows-latest

    steps:
      - run: echo "mew"
